[package]
name = "gg-asteroid"
version = "0.1.0"
authors = ["Adam Hoddinott <adam.hoddinott@salespreso.com>"]

[dependencies]
ggez = "0.4"
specs = { git = "https://github.com/slide-rs/specs.git" }
specs-derive = "*"
shred = "0.6.2"
shred-derive = "0.4"
geo = "0.7.4"
rand = "0.4"